### ISSUE TITLE
[Fix] 시간입력 dropdown qa fix

### ISSUE THREAD

**Issue by ljh0608** [ASAP-as-soon-as-possible/ASAP_Client#134]
## 🛠 Issue

- 가능 시간 입력 페이지 드롭다운 qa 

## 📝 To-do

- [ ] 30분 시간 비교 로직 
- [ ] 다음 버튼 비활성화면 넘어가지 않게
- [ ] 삭제 로직 예외처리
- [ ] 세개 확정시 폰트색깔 화이트
- [ ]
