### ISSUE TITLE
[Fix] 달력 오늘 이전 선택 날짜 막기

### ISSUE THREAD

**Issue by eastlaw80** [ASAP-as-soon-as-possible/ASAP_Client#168]
## 🛠 Issue
- 달력 오늘 이전 날짜를 선택할 수 없도록 선택 비활성화.
## 📝 To-do

- [ ] 모두의 시간 오늘 이전 날짜 예외처리 레퍼런스 확인
- [ ] 오늘 이전 날짜 선택 막기.
- [ ] 오늘 이전 날짜 전부 회색으로 색 처리
