### ISSUE TITLE
[Fix] 비밀번호 입력시 숫자 키패드 오픈

### ISSUE THREAD

**Issue by eastlaw80** [ASAP-as-soon-as-possible/ASAP_Client#202]
## 🛠 Issue

- 방장 입장을 위해 비밀번호 입력시에 쿼티자판이 아니라, 숫자 키패드가 올라오도록 수정.
## 📝 To-do

- [ ] placeholder 숫자 4자 이상으로
- [ ] 숫자 키패드 올라오도록
- [ ] 숫자 이외의 문자 들어가면 다음버튼 비활성화되도록
