### ISSUE TITLE
[Feat] 우선순위 입력 시간표 UI 변경

### ISSUE THREAD

**Issue by simeunseo** [ASAP-as-soon-as-possible/ASAP_Client#285]
## 🛠 Issue

![image](https://github.com/user-attachments/assets/241fc294-2e34-4e11-a865-48be5a07bbd4)
전(좌) -> 후(우)로 변경

## 📝 To-do

- [ ] 30분 단위 점선 삭제
- [ ] 한 slot의 height 줄임
- [ ] '우선순위를 입력해주세요' 밑에 subtitle 추가
